spring:
  application:
    name: jwt-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/lottery
    username: postgres
    password: sorokovsky17
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  access-token-key: '{"kty" : "oct","use" : "sig","kid" : "fd28e025-8d24-48bc-a51a-e2ffc8bc274b", k: "lczE94iiYk8XJce4QRFFBWZdTn8xACNolczE94iiYk8XJce4QRFFBWZdTn8xACNolczE94iiYk8XJce4QRFFBWZdTn8xACNo"}'
  refresh-token-key: '{"kty" : "oct","use" : "sig","kid" : "fd28e025-8d24-48bc-a51a-e2ffc8bc274b", k: "lczE94iiYk8XJce4QRFFBWZdTn8xACNo"}'