spring:
  application:
    name: jwt-auth
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5430/auth
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update