spring:
  application:
    name: jwt-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/lottery
    username: postgres
    password: sorokovsky17
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  access-token-key: o9th4g0J-n84Tf66iykXuoCJdC3ma5dgwYPUNA0-4AM=
  refresh-token-key: o9th4g0J-n84Tf66iykXuoCJdC3ma5dgwYPUNA0-4AM=